server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USERNAME:delivery}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET:c2VjcmV0b0xhcmdvU2VncmV0b0hNVlNvbG9IdW1vVXNhZG9TZWd1cm8yMDI0IQ==}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
