services:
  db:
    image: postgres:15-alpine
    container_name: delivery-db
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/auth_db
      DB_USERNAME: delivery
      DB_PASSWORD: admin
      JWT_SECRET: microservicios-secreto-firma-jwt-super-seguro-2024!!
      JWT_EXPIRATION_MS: 86400000

  catalogo-service:
    build:
      context: .
      dockerfile: catalogo-service/Dockerfile
    container_name: catalogo-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/catalogo_db
      DB_USERNAME: delivery
      DB_PASSWORD: admin
      INTERNAL_API_KEY: internal-super-key-2024

  pedidos-service:
    build:
      context: .
      dockerfile: pedidos-service/Dockerfile
    container_name: pedidos-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/pedidos_db
      DB_USERNAME: delivery
      DB_PASSWORD: admin
      INTERNAL_API_KEY: internal-super-key-2024
      CATALOGO_URL: http://catalogo-service:8082

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
      - catalogo-service
      - pedidos-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      CATALOGO_SERVICE_URL: http://catalogo-service:8082
      PEDIDOS_SERVICE_URL: http://pedidos-service:8083
      JWT_SECRET: microservicios-secreto-firma-jwt-super-seguro-2024!!
    ports:
      - "8080:8080"

volumes:
  db-data:
