server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CorrelationIdFilter
        - id: auth-service-registro
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/registro
          filters:
            - name: CorrelationIdFilter
        - id: catalogo-service
          uri: ${CATALOGO_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/comercios/**
          filters:
            - name: CorrelationIdFilter
            - name: JwtFilter
        - id: pedidos-service
          uri: ${PEDIDOS_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/pedidos/**
          filters:
            - name: CorrelationIdFilter
            - name: JwtFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: ${JWT_SECRET:c2VjcmV0b0xhcmdvU2VncmV0b0hNVlNvbG9IdW1vVXNhZG9TZWd1cm8yMDI0IQ==}
    expiration-ms: 86400000
