server:
  port: 8083

spring:
  application:
    name: pedidos-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pedidos_db}
    username: ${DB_USERNAME:delivery}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

internal:
  api-key: ${INTERNAL_API_KEY:internal-super-key-2024}

catalogo:
  url: ${CATALOGO_URL:http://localhost:8082}

resilience4j:
  circuitbreaker:
    instances:
      catalogoClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      catalogoClient:
        timeoutDuration: 10s
  retry:
    instances:
      catalogoClient:
        maxAttempts: 3
        waitDuration: 1s
